# Generated by Django 2.1.2 on 2018-10-15 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaughtPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=('M', 'Male'), max_length=6)),
                ('nickname', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('capture_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PokedexPokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
                ('type1', models.CharField(max_length=10)),
                ('type2', models.CharField(max_length=10)),
                ('art_url', models.CharField(max_length=200)),
                ('early_art_url', models.CharField(max_length=200)),
                ('early_jp_art_url', models.CharField(max_length=200)),
                ('icon_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='caughtpokemon',
            name='pokedex_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.PokedexPokemon'),
        ),
        migrations.AddField(
            model_name='caughtpokemon',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
