# Generated by Django 2.1.2 on 2018-10-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caughtpokemon',
            name='preferred_img',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='gender',
            field=models.CharField(blank=True, choices=[('♂', '♂'), ('♀', '♀'), ('', '')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
