# Generated by Django 2.1.2 on 2018-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caughtpokemon',
            name='preferred_art',
            field=models.IntegerField(choices=[(1, 'Original Suigomoto'), (2, 'Early Art'), (3, 'Early JP Art')], default=1),
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='gender',
            field=models.CharField(blank=True, choices=[('♂', '♂'), ('♀', '♀'), ('', '')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
