# Generated by Django 2.1.2 on 2018-10-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181018_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='preferred_img',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
