# Generated by Django 2.1.2 on 2018-10-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20181018_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='gender',
            field=models.CharField(blank=True, choices=[('♂', '♂'), ('♀', '♀'), (None, '')], max_length=1, null=True),
        ),
    ]
