# Generated by Django 2.1.2 on 2018-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20181018_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='gender',
            field=models.CharField(blank=True, choices=[('♂', '♂'), ('♀', '♀'), ('', '')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='caughtpokemon',
            name='preferred_img',
            field=models.IntegerField(blank=True, choices=[('Original Suigomoto', 1), ('Early Art', 2), ('Early JP Art', 3)], null=True),
        ),
    ]
