# Generated by Django 2.1.2 on 2018-10-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20181018_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='preferred_img',
            field=models.IntegerField(blank=True, choices=[(1, 'Original Suigomoto'), (2, 'Early Art'), (3, 'Early JP Art')], null=True),
        ),
    ]
