# Generated by Django 2.1.2 on 2018-10-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181018_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caughtpokemon',
            name='preferred_img',
        ),
        migrations.AddField(
            model_name='caughtpokemon',
            name='preferred_art',
            field=models.IntegerField(choices=[(1, 'Original Suigomoto'), (2, 'Early Art'), (3, 'Early JP Art')], default=1),
            preserve_default=False,
        ),
    ]
