# Generated by Django 2.1.2 on 2018-10-19 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20181018_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtpokemon',
            name='preferred_art',
            field=models.IntegerField(choices=[(1, 'Original Suigomoto'), (2, 'Early Art'), (3, 'Early JP Art')], default=1),
        ),
        migrations.AlterField(
            model_name='pokedexpokemon',
            name='min_lvl',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
