# Generated by Django 2.1.2 on 2018-10-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20181019_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedexpokemon',
            name='min_lvl',
            field=models.IntegerField(),
        ),
    ]
